<a href="https://colab.research.google.com/github/malishilpa9119/LSTM_next_word_predictor/blob/main/Next_Word_Predictor_Using_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
faqs = """General Technology FAQ

What is technology?
Technology refers to the practical use of scientific knowledge for creating tools, systems, and processes that solve problems and improve human life.

How does a computer work?
A computer processes data using hardware components like the CPU, memory, and storage, along with software that gives instructions to perform tasks.

What are the main parts of a computer?
A typical computer includes a central processing unit (CPU), monitor, keyboard, mouse, memory, storage device, and sometimes a graphics processing unit (GPU).

What is the difference between hardware and software?
Hardware is the physical part of a computer like a keyboard or hard drive, while software refers to programs or code that run on the hardware.

What is the Internet?
The Internet is a global network of computers connected to share data and communicate using standardized protocols such as TCP/IP.

How does Wi-Fi work?
Wi-Fi uses radio waves to transmit data wirelessly between a router and a device, allowing access to the internet without physical cables.

What is cloud computing?
Cloud computing allows users to store, manage, and process data on remote servers accessed via the internet instead of local systems.

What are examples of cloud services?
Common examples include Google Drive, Amazon Web Services (AWS), Microsoft Azure, and Dropbox.

What is artificial intelligence?
Artificial Intelligence (AI) is the simulation of human intelligence in machines, enabling them to perform tasks such as learning, reasoning, and decision-making.

What is machine learning?
Machine Learning (ML) is a subset of AI that enables systems to automatically learn patterns from data and make predictions without explicit programming.

What is data science?
Data Science involves collecting, analyzing, and interpreting large volumes of data to extract meaningful insights and support decision-making.

What is cybersecurity?
Cybersecurity refers to the protection of computer systems and networks from unauthorized access, attacks, or damage.

How can I protect my computer from viruses?
You can protect your computer by installing antivirus software, keeping your system updated, avoiding suspicious links, and not downloading unknown files.

What is encryption?
Encryption is the process of converting information into a secret code to protect it from unauthorized access.

What is a programming language?
A programming language is a set of instructions and syntax that allows humans to communicate with computers to develop software and applications.

Which are the most popular programming languages?
Some widely used languages include Python, Java, C++, JavaScript, and SQL.

What is Python used for?
Python is used for web development, data analysis, machine learning, automation, and scripting due to its simplicity and versatility.

What is the difference between frontend and backend development?
Frontend development deals with what users see in a web application, while backend development handles the server logic, databases, and API connections.

What is an API?
An API (Application Programming Interface) allows different software applications to communicate and share data with each other.

What is a database?
A database is an organized collection of data that can be easily accessed, managed, and updated electronically.

What is SQL?
SQL (Structured Query Language) is used to manage and manipulate data stored in relational databases.

What is Git?
Git is a version control system that tracks changes in source code, allowing developers to collaborate efficiently.

What is GitHub?
GitHub is an online platform that hosts Git repositories and provides tools for version control and collaboration.

What is artificial neural network?
An artificial neural network is a computational model inspired by the human brain, consisting of layers of nodes that process information.

What is the Internet of Things (IoT)?
IoT refers to the network of physical devices connected to the internet that collect and share data, such as smartwatches and home sensors.

What is blockchain technology?
Blockchain is a decentralized digital ledger that records transactions securely and transparently across multiple computers.

What is virtual reality?
Virtual Reality (VR) is a computer-generated simulation of an environment that users can interact with using special headsets and controllers.

What is augmented reality?
Augmented Reality (AR) overlays digital information such as images or text on the real-world view using devices like smartphones or AR glasses.

What is 5G technology?
5G is the fifth generation of mobile networks, offering higher speed, lower latency, and more reliable connections than previous generations.

What is automation?
Automation is the use of technology to perform tasks with minimal human intervention, often improving efficiency and accuracy.

What is big data?
Big data refers to extremely large datasets that require advanced tools and techniques to store, process, and analyze.

What is cloud storage?
Cloud storage allows you to save data on remote servers managed by cloud providers, making it accessible anytime from anywhere.

What is the difference between RAM and ROM?
RAM is temporary memory used while a computer is running, while ROM is permanent memory that stores essential startup instructions.

What is an operating system?
An operating system (OS) manages computer hardware and software resources, enabling interaction between users and devices. Examples include Windows, macOS, and Linux.

What is open-source software?
Open-source software is software whose source code is freely available for anyone to view, modify, and distribute.

What is version control?
Version control is the practice of tracking and managing changes to code, ensuring teams can collaborate efficiently without overwriting each other's work.

What is artificial general intelligence (AGI)?
AGI is a hypothetical form of AI that can understand, learn, and perform any intellectual task that a human can.

What is a chatbot?
A chatbot is an AI-based program designed to simulate human conversation through text or voice interactions.

What is the difference between AI and ML?
AI is a broader concept of machines performing intelligent tasks, while ML is a specific method that allows machines to learn from data.

How does deep learning work?
Deep learning uses multiple layers of neural networks to learn representations of data automatically, often used in image and speech recognition.

What is a GPU and why is it used in AI?
A GPU (Graphics Processing Unit) accelerates mathematical computations, making it ideal for training deep learning models.

What is an algorithm?
An algorithm is a step-by-step procedure or formula for solving a problem or performing a computation.

What is computer vision?
Computer vision is a field of AI that enables computers to interpret and understand visual information from the world.

How do search engines work?
Search engines crawl the web, index pages, and use ranking algorithms to display the most relevant results for a user query.

How can I stay updated with the latest technology trends?
You can follow tech blogs, podcasts, newsletters, and YouTube channels that discuss new innovations and tools in the tech world.

"""


In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
import numpy as np

In [ ]:
tokenizer = Tokenizer()

In [ ]:
tokenizer.fit_on_texts([faqs])

In [ ]:
len(tokenizer.word_index)

434

In [ ]:
input_sequences = []
for sentence in faqs.split('\n'):
  tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]

  for i in range(1,len(tokenized_sentence)):
    input_sequences.append(tokenized_sentence[:i+1])

In [ ]:
input_sequences

[[96, 17],
 [96, 17, 170],
 [3, 1],
 [3, 1, 17],
 [17, 28],
 [17, 28, 5],
 [17, 28, 5, 6],
 [17, 28, 5, 6, 171],
 [17, 28, 5, 6, 171, 64],
 [17, 28, 5, 6, 171, 64, 7],
 [17, 28, 5, 6, 171, 64, 7, 172],
 [17, 28, 5, 6, 171, 64, 7, 172, 173],
 [17, 28, 5, 6, 171, 64, 7, 172, 173, 14],
 [17, 28, 5, 6, 171, 64, 7, 172, 173, 14, 174],
 [17, 28, 5, 6, 171, 64, 7, 172, 173, 14, 174, 36],
 [17, 28, 5, 6, 171, 64, 7, 172, 173, 14, 174, 36, 37],
 [17, 28, 5, 6, 171, 64, 7, 172, 173, 14, 174, 36, 37, 2],
 [17, 28, 5, 6, 171, 64, 7, 172, 173, 14, 174, 36, 37, 2, 97],
 [17, 28, 5, 6, 171, 64, 7, 172, 173, 14, 174, 36, 37, 2, 97, 8],
 [17, 28, 5, 6, 171, 64, 7, 172, 173, 14, 174, 36, 37, 2, 97, 8, 175],
 [17, 28, 5, 6, 171, 64, 7, 172, 173, 14, 174, 36, 37, 2, 97, 8, 175, 176],
 [17, 28, 5, 6, 171, 64, 7, 172, 173, 14, 174, 36, 37, 2, 97, 8, 175, 176, 2],
 [17,
  28,
  5,
  6,
  171,
  64,
  7,
  172,
  173,
  14,
  174,
  36,
  37,
  2,
  97,
  8,
  175,
  176,
  2,
  177],
 [17,
  28,
  5,
  6,
  

In [ ]:
max_len = max([len(x) for x in input_sequences])

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences = pad_sequences(input_sequences, maxlen = max_len, padding = 'pre')

In [ ]:
padded_input_sequences

array([[  0,   0,   0, ...,   0,  96,  17],
       [  0,   0,   0, ...,  96,  17, 170],
       [  0,   0,   0, ...,   0,   3,   1],
       ...,
       [  0,   0,   0, ...,  36,  19,   6],
       [  0,   0,   0, ...,  19,   6, 169],
       [  0,   0,   0, ...,   6, 169,  94]], dtype=int32)

In [ ]:
X = padded_input_sequences[:,:-1]

In [ ]:
y = padded_input_sequences[:,-1]

In [ ]:
X.shape

(1024, 25)

In [ ]:
y.shape

(1024,)

In [ ]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y,num_classes=435)

In [ ]:
y.shape

(1024, 435)

In [ ]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [ ]:
model = Sequential()
model.add(Embedding(435, 100, input_length=26))
model.add(LSTM(150))
model.add(Dense(435, activation='softmax'))

In [ ]:
model.compile(loss = 'categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
model.build(input_shape=(None, 25))
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 25, 100)        │        43,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 150)            │       150,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 435)            │        65,685 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 259,785 (1014.79 KB)

 Trainable params: 259,785 (1014.79 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
X

array([[  0,   0,   0, ...,   0,   0,  96],
       [  0,   0,   0, ...,   0,  96,  17],
       [  0,   0,   0, ...,   0,   0,   3],
       ...,
       [  0,   0,   0, ...,   2,  36,  19],
       [  0,   0,   0, ...,  36,  19,   6],
       [  0,   0,   0, ...,  19,   6, 169]], dtype=int32)

In [ ]:
model.fit(X,y,epochs=100)

Epoch 1/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 4s 50ms/step - accuracy: 0.0568 - loss: 5.9704
Epoch 2/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.1032 - loss: 5.4659
Epoch 3/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 2s 51ms/step - accuracy: 0.0978 - loss: 5.3220
Epoch 4/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 2s 49ms/step - accuracy: 0.0922 - loss: 5.1615
Epoch 5/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 2s 61ms/step - accuracy: 0.1119 - loss: 5.0455
Epoch 6/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 3s 86ms/step - accuracy: 0.1372 - loss: 4.8926
Epoch 7/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 2s 49ms/step - accuracy: 0.1319 - loss: 4.7664
Epoch 8/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step - accuracy: 0.1413 - loss: 4.6708
Epoch 9/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 3s 49ms/step - accuracy: 0.1511 - loss: 4.5030
Epoch 10/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 2s 52ms/step - accuracy: 0.1604 - loss: 4.2877
Epoch 11/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 2s 49ms/step - accuracy: 0.1589 - loss: 4.1903
Epoch 12/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 3s 83ms/step

In [ ]:
text = "programming"

for i in range(5):
  # tokenize
  token_text = tokenizer.texts_to_sequences([text])[0]
  # padding
  padded_token_text = pad_sequences([token_text], maxlen=25, padding='pre')
  # predict
  pos = np.argmax(model.predict(padded_token_text))

  for word, index in tokenizer.word_index.items():
    if index == pos:
      # print(word)
      text = text + " " + word
      print(text)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
programming language
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
programming language is
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
programming language is a
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step
programming language is a decentralized
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
programming language is a decentralized digital
